channels:
- defaults
- conda-forge
dependencies:
- python=3.12
- pip
- pip:
  - mlflow==3.4.0
  - tensorflow==2.20.0
  - numpy>=1.26.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - gensim>=4.3.2
  - nltk>=3.9.0
name: word2vec_sentiment_env
